import peewee
from playhouse.postgres_ext import PostgresqlExtDatabase
from crawler.models import db, ManagementUnit, Evaluation

DATA = [
    ("Prefeitura de João Pessoa", "João Pessoa", "https://transparencia.joaopessoa.pb.gov.br/"),
    ("Prefeitura de Campina Grande", "Campina Grande", "https://campinagrande.pb.gov.br/portal-da-transparencia/"),
    ("Prefeitura de Patos", "Patos", "https://patos.pb.gov.br/servicos/portal_da_transparencia"),
    ("Prefeitura de Bayeux", "Bayeux", "https://transparencia.bayeux.pb.gov.br/"),
    ("Prefeitura de Sousa", "Sousa", "https://www.sousa.pb.gov.br/portal-da-transparencia.php"),
    ("Prefeitura de Cabedelo", "Cabedelo", "https://cabedelo.pb.gov.br/portal-da-transparencia/"),
    ("Prefeitura de Mamanguape", "Mamanguape", "https://www.mamanguape.pb.gov.br/portal-da-transparencia/"),
    ("Prefeitura de Queimadas", "Queimadas", "https://www.queimadas.pb.gov.br/portal/transparencia-fiscal"),
    ("Prefeitura de Monteiro", "Monteiro", "https://www.monteiro.pb.gov.br/portal-da-transparencia/"),
    ("Prefeitura de Pombal", "Pombal", "https://www.pombal.pb.gov.br/portal-da-transparencia/"),
    ("Prefeitura de Lagoa Seca", "Lagoa Seca", "https://lagoaseca.pb.gov.br/portal/transparencia-fiscal/"),
    ("Prefeitura de Solânea", "Solânea", "https://solanea.pb.gov.br/portal-da-transparencia/"),
    ("Prefeitura de Itaporanga", "Itaporanga", "https://itaporanga.pb.gov.br/assuntos/portal-da-transparencia"),
    ("Prefeitura de Rio Tinto", "Rio Tinto", "https://riotinto.pb.gov.br/transparenciafiscal.php"),
    ("Prefeitura de Areia", "Areia", "https://areia.pb.gov.br/portal-da-transparencia/"),
    ("Prefeitura de Bananeiras", "Bananeiras", "https://www.bananeiras.pb.gov.br/portal-da-transparencia/"),
    ("Prefeitura de Alagoa Nova", "Alagoa Nova", "https://alagoanova.pb.gov.br/portal-da-transparencia/"),
    ("Prefeitura de Araruna", "Araruna", "https://www.araruna.pb.gov.br/transparencia/"),
    ("Prefeitura de Remígio", "Remígio", "https://www.remigio.pb.gov.br/portal/transparencia-fiscal"),
    ("Prefeitura de Conceição", "Conceição", "https://conceicao.pb.gov.br/assuntos/portal-da-transparencia"),
    ("Prefeitura de Itapororoca", "Itapororoca", "https://itapororoca.pb.gov.br/transparencia-fiscal"),
    ("Prefeitura de Boqueirão", "Boqueirão", "https://www.boqueirao.pb.gov.br/portal/transparencia-fiscal"),
    ("Prefeitura de Cruz do Espírito Santo", "Cruz do Espírito Santo", "https://portaldatransparencia.publicsoft.com.br/sistemas/ContabilidadePublica/views/"),
    ("Prefeitura de Cacimba de Dentro", "Cacimba de Dentro", "https://www.cacimbadedentro.pb.gov.br/portal-da-transparencia/"),
    ("Prefeitura de Araçagi", "Araçagi", "https://www.aracagi.pb.gov.br/portal/transparencia-fiscal"),
    ("Prefeitura de Piancó", "Piancó", "https://pianco.pb.gov.br/assuntos/portal-da-transparencia"),
    ("Prefeitura de Uiraúna", "Uiraúna", "https://www.uirauna.pb.gov.br/transparenciafiscal.php"),
    ("Prefeitura de Teixeira", "Teixeira", "https://www.teixeira.pb.gov.br/portal/transparencia-fiscal"),
    ("Prefeitura de Soledade", "Soledade", "https://www.soledade.pb.gov.br/portal-da-transparencia/"),
    ("Prefeitura de Tavares", "Tavares", "https://tavares.pb.gov.br/assuntos/portal-da-transparencia"),
    ("Prefeitura de Puxinanã", "Puxinanã", "https://www.puxinana.pb.gov.br/portal/transparencia-fiscal"),
    ("Prefeitura de Paulista", "Paulista", "https://paulista.pb.gov.br/assuntos/portal-da-transparencia"),
    ("Prefeitura de Bonito de Santa Fé", "Bonito de Santa Fé", "https://www.bonitodesantafe.pb.gov.br/transparenciafiscal.php"),
    ("Prefeitura de Pilar", "Pilar", "https://www.pilar.pb.gov.br/portal/transparencia-fiscal"),
    ("Prefeitura de Juru", "Juru", "https://juru.pb.gov.br/assuntos/portal-da-transparencia"),
    ("Prefeitura de Baia da Traição", "Baia da Traição", "https://www.baiadatraicao.pb.gov.br/portal/transparencia-fiscal"),
    ("Prefeitura de Mataraca", "Mataraca", "https://www.mataraca.pb.gov.br/portal-da-transparencia/"),
    ("Prefeitura de Riacho dos Cavalos", "Riacho dos Cavalos", "https://riachodoscavalos.pb.gov.br/assuntos/portal-da-transparencia"),
    ("Prefeitura de Aparecida", "Aparecida", "https://aparecida.pb.gov.br/portal-da-transparencia.php"),
    ("Prefeitura de Barra de Santana", "Barra de Santana", "https://barradesantana.pb.gov.br/portal-da-transparencia/"),
    ("Prefeitura de Sobrado", "Sobrado", "https://sobrado.pb.gov.br/assuntos/portal-da-transparencia"),
    ("Prefeitura de Lagoa de Dentro", "Lagoa de Dentro", "https://lagoadedentro.pb.gov.br/transparencia/"),
    ("Prefeitura de Casserengue", "Casserengue", "https://www.casserengue.pb.gov.br/portal/transparencia-fiscal"),
    ("Prefeitura de São Miguel de Taipú", "São Miguel de Taipú", "https://www.saomigueldetaipu.pb.gov.br/portal/transparencia-fiscal"),
    ("Prefeitura de Belém do Brejo do Cruz", "Belém do Brejo do Cruz", "https://brejodocruz.pb.gov.br/portal-da-transparencia/"),
    ("Prefeitura de Nazarezinho", "Nazarezinho", "https://www.nazarezinho.pb.gov.br/portal-da-transparencia.php"),
    ("Prefeitura de Junco do Seridó", "Junco do Seridó", "https://juncodoserido.pb.gov.br/assuntos/portal-da-transparencia"),
    ("Prefeitura de Boa Vista", "Boa Vista", "https://www.boavista.pb.gov.br/transparencia-fiscal"),
    ("Prefeitura de Serra Redonda", "Serra Redonda", "https://serraredonda.pb.gov.br/assuntos/portal-da-transparencia"),
    ("Prefeitura de Santana dos Garrotes", "Santana dos Garrotes", "https://santanadosgarrotes.pb.gov.br/assuntos/portal-da-transparencia"),
    ("Prefeitura de Capim", "Capim", "https://www.capim.pb.gov.br/portal-da-transparencia/"),
    ("Prefeitura de Maturéia", "Maturéia", "https://matureia.pb.gov.br/assuntos/portal-da-transparencia"),
    ("Prefeitura de Marizópolis", "Marizópolis", "https://marizopolis.pb.gov.br/transparenciafiscal.php"),
    ("Prefeitura de Santa Cecília", "Santa Cecília", "https://cmsantacecilia.pb.gov.br/transparencia/"),
    ("Prefeitura de Pilões", "Pilões", "http://www.piloes.pb.gov.br/transparencia"),
    ("Prefeitura de Diamante", "Diamante", "https://diamante.pb.gov.br/assuntos/portal-da-transparencia"),
    ("Prefeitura de Cuité de Mamanguape", "Cuité de Mamanguape", "https://www.cuitedemamanguape.pb.gov.br/portal-da-transparencia/"),
    ("Prefeitura de Caldas Brandão", "Caldas Brandão", "https://www.caldasbrandao.pb.gov.br/transparencia/"),
    ("Prefeitura de São José dos Ramos", "São José dos Ramos", "https://www.saojosedosramos.pb.gov.br/transparenciafiscal.php"),
    ("Prefeitura de Nova Olinda", "Nova Olinda", "https://www.novaolinda.pb.gov.br/transparenciafiscal.php"),
    ("Prefeitura de Ibiara", "Ibiara", "https://ibiara.pb.gov.br/assuntos/portal-da-transparencia"),
    ("Prefeitura de Santa Helena", "Santa Helena", "https://www.santahelena.pb.gov.br/portal-da-transparencia.php"),
    ("Prefeitura de Montadas", "Montadas", "https://www.montadas.pb.gov.br/portal_da_transparencia/"),
    ("Prefeitura de Cabaceiras", "Cabaceiras", "https://cabaceiras.pb.gov.br/portal-da-transparencia/"),
    ("Prefeitura de Aguiar", "Aguiar", "https://aguiar.pb.gov.br/assuntos/portal-da-transparencia"),
    ("Prefeitura de Vieirópolis", "Vieirópolis", "https://www.vieiropolis.pb.gov.br/transparencia"),
    ("Prefeitura de Borborema", "Borborema", "https://borborema.pb.gov.br/portal-da-transparencia/"),
    ("Prefeitura de Boa Ventura", "Boa Ventura", "https://boaventura.pb.gov.br/assuntos/portal-da-transparencia"),
    ("Prefeitura de Santana de Mangueira", "Santana de Mangueira", "https://santanademangueira.pb.gov.br/assuntos/portal-da-transparencia"),
    ("Prefeitura de Caturité", "Caturité", "https://www.caturite.pb.gov.br/transparencia-fiscal"),
    ("Prefeitura de Congo", "Congo", "https://www.congo.pb.gov.br/portal/transparencia-fiscal"),
    ("Prefeitura de Riachão do Poço", "Riachão do Poço", "https://www.riachaodopoco.pb.gov.br/transparencia-fiscal"),
    ("Prefeitura de Matinhas", "Matinhas", "https://matinhas.pb.gov.br/"),
    ("Prefeitura de Logradouro", "Logradouro", "https://www.logradouro.pb.gov.br/transparencia/"),
    ("Prefeitura de Poço de José de Moura", "Poço de José de Moura", "https://pocodejosedemoura.pb.gov.br/transparencia/"),
    ("Prefeitura de São João do Cariri", "São João do Cariri", "https://saojoaodocariri.pb.gov.br/transparencia"),
    ("Prefeitura de Mãe d'Água", "Mãe d'Água", "https://maedagua.pb.gov.br/assuntos/portal-da-transparencia"),
    ("Prefeitura de Vista Serrana", "Vista Serrana", "https://vistaserrana.pb.gov.br/assuntos/portal-da-transparencia"),
    ("Prefeitura de Pedra Branca", "Pedra Branca", "https://www.pedrabranca.pb.gov.br/transparenciafiscal.php"),
    ("Prefeitura de Cacimba de Areia", "Cacimba de Areia", "https://cacimbadeareia.pb.gov.br/assuntos/portal-da-transparencia"),
    ("Prefeitura de Riachão", "Riachão", "https://www.riachao.pb.gov.br/portal-da-transparencia/"),
    ("Prefeitura de Dona Inês", "Dona Inês", "https://transparencia.pmdonaines.pb.gov.br/"),
    ("Prefeitura de Santa Inês", "Santa Inês", "https://www.santaines.pb.gov.br/transparencia"),
    ("Prefeitura de Emas", "Emas", "https://emas.pb.gov.br/assuntos/portal-da-transparencia"),
    ("Prefeitura de Tenório", "Tenório", "https://tenorio.pb.gov.br/assuntos/portal-da-transparencia"),
    ("Prefeitura de Ouro Velho", "Ouro Velho", "https://transparencia.ourovelho.pb.gov.br/"),
    ("Prefeitura de Várzea", "Várzea", "https://varzea.pb.gov.br/assuntos/portal-da-transparencia"),
    ("Prefeitura de Lastro", "Lastro", "https://www.lastro.pb.gov.br/2021novo/transparencia.html"),
    ("Prefeitura de Joca Claudino", "Joca Claudino", "https://www.jocaclaudino.pb.gov.br/portal-da-transparencia.php"),
    ("Prefeitura de Amparo", "Amparo", "https://amparo.pb.gov.br/transparencia/"),
    ("Prefeitura de Quixaba", "Quixaba", "https://quixaba.pb.gov.br/assuntos/portal-da-transparencia"),
    ("Prefeitura de Livramento", "Livramento", "https://livramento.pb.gov.br/assuntos/portal-da-transparencia"),
    ("Prefeitura de Areial", "Areial", "https://areial.pb.gov.br/transparencia/"),
    ("Prefeitura de Condado", "Condado", "https://condado.pb.gov.br/assuntos/portal-da-transparencia"),
    ("Prefeitura de Camalaú", "Camalaú", "https://camalau.pb.gov.br/assuntos/portal-da-transparencia"),
    ("Prefeitura de Alcantil", "Alcantil", "https://alcantil.pb.gov.br/portaldatransparencia/"),
    ("Prefeitura de Assunção", "Assunção", "https://www.assuncao.pb.gov.br/portal/transparencia-fiscal"),
    ("Prefeitura de Sossêgo", "Sossêgo", "https://www.sossego.pb.gov.br/portal/transparencia-fiscal"),
    ("Prefeitura de São José dos Cordeiros", "São José dos Cordeiros", "https://transparenciaativa.com.br/Principal.aspx?Entidade=71"),
    ("Prefeitura de Bernardino Batista", "Bernardino Batista", "https://www.bernardinobatista.pb.gov.br/portal/transparencia-fiscal"),
    ("Prefeitura de São Domingos", "São Domingos", "https://saodomingos.pb.gov.br/transparencia/portal-da-transparencia"),
    ("Prefeitura de Serra da Raiz", "Serra da Raiz", "https://www.serradaraiz.pb.gov.br/portal-da-transparencia/"),
    ("Prefeitura de Algodão de Jandaíra", "Algodão de Jandaíra", "https://algodaodejandaira.pb.gov.br/transparencia/"),
    ("Prefeitura de Santo André", "Santo André", "https://santoandre.pb.gov.br/transparencia"),
    ("Prefeitura de Riacho de Santo Antônio", "Riacho de Santo Antônio", "https://riachodesantoantonio.pb.gov.br/transparencia/"),
    ("Prefeitura de Parari", "Parari", "http://www.parari.pb.gov.br/transparencia/"),
    ("Prefeitura de Santa Rita", "Santa Rita", "https://www.santarita.pb.gov.br/portal-da-transparencia/"),
    ("Prefeitura de Cajazeiras", "Cajazeiras", "https://cajazeiras.pb.gov.br/transparenciafiscal.php"),
    ("Prefeitura de Pedras de Fogo", "Pedras de Fogo", "https://www.pedrasdefogo.pb.gov.br/transparencia-inicio"),
    ("Prefeitura de Alhandra", "Alhandra", "https://www.alhandra.pb.gov.br/transparencia/"),
    ("Prefeitura de Juazeirinho", "Juazeirinho", "https://juazeirinho.pb.gov.br/portal-da-transparencia/inicio"),
    ("Prefeitura de Santa Luzia", "Santa Luzia", "https://santaluzia.pb.gov.br/assuntos/portal-da-transparencia"),
    ("Prefeitura de Coremas", "Coremas", "https://coremas.pb.gov.br/transparenciafiscal.php"),
    ("Prefeitura de Alagoinha", "Alagoinha", "https://alagoinha.pb.gov.br/transparencia/"),
    ("Prefeitura de Serra Branca", "Serra Branca", "https://www.serrabranca.pb.gov.br/transparencia/"),
    ("Prefeitura de Lucena", "Lucena", "https://www.lucena.pb.gov.br/transparencia/"),
    ("Prefeitura de Mogeiro", "Mogeiro", "https://mogeiro.pb.gov.br/portal-da-transparencia/"),
    ("Prefeitura de Imaculada", "Imaculada", "https://imaculada.pb.gov.br/assuntos/portal-da-transparencia"),
    ("Prefeitura de Mulungú", "Mulungú", "https://mulungu.pb.gov.br/transparencia/"),
    ("Prefeitura de Desterro", "Desterro", "https://siteseticons.com.br/portal/ws/empresa/MDg5MjU5NjgwMDAxMzA=/inicio"),
    ("Prefeitura de Juarez Távora", "Juarez Távora", "https://www.juareztavora.pb.gov.br/transparencia/"),
    ("Prefeitura de São Mamede", "São Mamede", "https://saomamede.pb.gov.br/assuntos/portal-da-transparencia"),
    ("Prefeitura de Cacimbas", "Cacimbas", "https://siteseticons.com.br/portal/ws/empresa/MDE2MTI2ODYwMDAxMzQ=/inicio"),
    ("Prefeitura de Caiçara", "Caiçara", "https://www.caicara.pb.gov.br/portal-da-transparencia/"),
    ("Prefeitura de Cuitegi", "Cuitegi", "https://cuitegi.pb.gov.br/transparencia/"),
    ("Prefeitura de São José de Caiana", "São José de Caiana", "https://saojosedecaiana.pb.gov.br/assuntos/portal-da-transparencia"),
    ("Prefeitura de Igaracy", "Igaracy", "https://www.igaracy.pb.gov.br/index.php/transparencia/portal-da-transparencia"),
    ("Prefeitura de Malta", "Malta", "https://malta.pb.gov.br/assuntos/portal-da-transparencia"),
    ("Prefeitura de Catingueira", "Catingueira", "https://catingueira.pb.gov.br/assuntos/portal-da-transparencia"),
    ("Prefeitura de São José de Espinharas", "São José de Espinharas", "https://saojosedeespinharas.pb.gov.br/assuntos/portal-da-transparencia"),
    ("Prefeitura de São Bentinho", "São Bentinho", "https://siteseticons.com.br/portal/ws/empresa/MDE2MTI2OTAwMDAxMDA=/inicio"),
    ("Prefeitura de Riachão do Bacamarte", "Riachão do Bacamarte", "https://siteseticons.com.br/portal/ws/empresa/MDE2MTIzNDMwMDAxNzA=/inicio"),
    ("Prefeitura de Santa Terezinha", "Santa Terezinha", "https://santaterezinha.pb.gov.br/assuntos/portal-da-transparencia"),
    ("Prefeitura de São João do Tigre", "São João do Tigre", "https://saojoaodotigre.pb.gov.br/transparencia/"),
    ("Prefeitura de Prata", "Prata", "https://transparencia.prata.pb.gov.br/"),
    ("Prefeitura de São José do Sabugi", "São José do Sabugi", "https://saojosedosabugi.pb.gov.br/assuntos/portal-da-transparencia"),
    ("Prefeitura de Olivêdos", "Olivêdos", "https://olivedos.pb.gov.br/transparencia/"),
    ("Prefeitura de São José de Princesa", "São José de Princesa", "https://www.saojosedeprincesa.pb.gov.br/transparencia/ "),
    ("Prefeitura de São José do Bonfim", "São José do Bonfim", "https://saojosedobonfim.pb.gov.br/assuntos/portal-da-transparencia"),
    ("Prefeitura de São Sebastião do Umbuzeiro", "São Sebastião do Umbuzeiro", "https://ssdoumbuzeiro.pb.gov.br/transparencia/"),
    ("Prefeitura de Cajazeirinhas", "Cajazeirinhas", "https://www.cajazeirinhas.pb.gov.br/transparencia.html"),
    ("Prefeitura de Serra Grande", "Serra Grande", "https://serragrande.pb.gov.br/transparenciafiscal.php"),
    ("Prefeitura de Curral Velho", "Curral Velho", "https://curralvelho.pb.gov.br/assuntos/portal-da-transparencia"),
    ("Prefeitura de Passagem", "Passagem", "https://passagem.pb.gov.br/assuntos/portal-da-transparencia"),
    ("Prefeitura de Zabelê", "Zabelê", "https://www.zabele.pb.gov.br/transparencia/"),
    ("Prefeitura de São Vicente do Seridó", "São Vicente do Seridó", "https://saovicentedoserido.pb.gov.br/transparencia"),
    ("Prefeitura de Nova Floresta", "Nova Floresta", "https://novafloresta.pb.gov.br/transparencia-fiscal"),
    ("Prefeitura de Pirpirituba", "Pirpirituba", "https://www.pirpirituba.pb.gov.br/transparencia-fiscal"),
    ("Prefeitura de Água Branca", "Água Branca", "https://transparencia.aguabranca.pb.gov.br/publico"),
    ("Prefeitura de Cachoeira dos Índios", "Cachoeira dos Índios", "https://www.cachoeiradosindios.pb.gov.br/transparenciafiscal.php"),
    ("Prefeitura de Triunfo", "Triunfo", "https://www.triunfo.pb.gov.br/transparencia/"),
    ("Prefeitura de Marcação", "Marcação", "https://www.marcacao.pb.gov.br/transparencia-fiscal"),
    ("Prefeitura de Pedra Lavrada", "Pedra Lavrada", "https://pedralavrada.pb.gov.br/transparencia"),
    ("Prefeitura de Cubati", "Cubati", "https://cubati.pb.gov.br/portal-da-transparencia/"),
    ("Prefeitura de São José da Lagoa Tapada", "São José da Lagoa Tapada", "https://saojoselt.pb.gov.br/assuntos/portal-da-transparencia"),
    ("Prefeitura de Santa Cruz", "Santa Cruz", "https://www.santacruz.pb.gov.br/portal-da-transparencia.php"),
    ("Prefeitura de Olho d'Água", "Olho d'Água", "https://transparencia.elmartecnologia.com.br/?e=201130"),
    ("Prefeitura de Pedro Régis", "Pedro Régis", "https://www.pedroregis.pb.gov.br/portal/transparencia-fiscal  "),
    ("Prefeitura de Barra de São Miguel", "Barra de São Miguel", "https://www.barradesaomiguel.pb.gov.br/portal/transparencia-fiscal  "),
    ("Prefeitura de Serraria", "Serraria", "https://www.serraria.pb.gov.br/portal-da-transparencia/"),
    ("Prefeitura de Damião", "Damião", "https://www.damiao.pb.gov.br/portal-da-transparencia/"),
    ("Prefeitura de Sertãozinho", "Sertãozinho", "https://www.sertaozinho.pb.gov.br/portal-da-transparencia/"),
    ("Prefeitura de Baraúna", "Baraúna", "https://barauna.pb.gov.br/transparencia/"),
    ("Prefeitura de Nova Palmeira", "Nova Palmeira", "https://novapalmeira.pb.gov.br/link/transparencia.html"),
    ("Prefeitura de Pilõezinhos", "Pilõezinhos", "https://piloezinhos.pb.gov.br/transparencia/"),
    ("Prefeitura de Monte Horebe", "Monte Horebe", "https://montehorebe.pb.gov.br/transparencia.html"),
    ("Prefeitura de Lagoa", "Lagoa", "https://transparencia.elmartecnologia.com.br/?e=201101"),
    ("Prefeitura de Caraúbas", "Caraúbas", "https://caraubas.pb.gov.br/transparencia/"),
    ("Prefeitura de Salgadinho", "Salgadinho", "https://salgadinho.pb.gov.br/assuntos/portal-da-transparencia "),
    ("Prefeitura de Duas Estradas", "Duas Estradas", "https://www.duasestradas.pb.gov.br/portal-da-transparencia/"),
    ("Prefeitura de Gurjão", "Gurjão", "http://www.gurjao.pb.gov.br/inicio/transparencia/"),
    ("Prefeitura de São Francisco", "São Francisco", "https://www.saofrancisco.pb.gov.br/transparenciafiscal.php"),
    ("Prefeitura de Frei Martinho", "Frei Martinho", "https://www.freimartinho.pb.gov.br/portal/transparencia-fiscal"),
    ("Prefeitura de Carrapateira", "Carrapateira", "https://transparencia.elmartecnologia.com.br/?e=201054&DefaultLayout="),
    ("Prefeitura de São Domingos do Cariri", "São Domingos do Cariri", "https://transparencia.elmartecnologia.com.br/?e=201180"),
    ("Prefeitura de Bom Jesus", "Bom Jesus", "https://www.prefeiturabomjesus.pb.gov.br/transparenciafiscal.php"),
    ("Prefeitura de Areia de Baraúnas", "Areia de Baraúnas", "https://areiadebaraunas.pb.gov.br/assuntos/portal-da-transparencia"),
    ("Prefeitura de Coxixola", "Coxixola", "https://coxixola.pb.gov.br/transparencia/"),
    ("Prefeitura de Poço Dantas", "Poço Dantas", "https://www.pocodantas.pb.gov.br/portal/transparencia-fiscal"),
    ("Prefeitura de Catolé do Rocha", "Catolé do Rocha", "https://catoledorocha.pb.gov.br/assuntos/portal-da-transparencia"),
    ("Prefeitura de Bom Sucesso", "Bom Sucesso", "https://www.bomsucesso.pb.gov.br/portal-da-transparencia.php"),
    ("Prefeitura de Mato Grosso", "Mato Grosso", "https://transparencia.matogrosso.pb.gov.br/"),
    ("Prefeitura de São José do Brejo do Cruz", "São José do Brejo do Cruz", "https://saojosedobrejodocruz.pb.gov.br/portal-da-transparencia/"),
    ("Prefeitura de Brejo do Cruz", "Brejo do Cruz", "https://brejodocruz.pb.gov.br/portal-da-transparencia/  "),
    ("Prefeitura de Curral de Cima", "Curral de Cima", "https://www.curraldecima.pb.gov.br/portal-da-transparencia/"),
    ("Prefeitura de Manaíra", "Manaíra", "https://manaira.pb.gov.br/assuntos/portal-da-transparencia"),
    ("Prefeitura de Sapé", "Sapé", "https://sape.pb.gov.br/portal-da-transparencia/"),
    ("Prefeitura de Esperança", "Esperança", "https://www.esperanca.pb.gov.br/portal/transparencia-fiscal"),
    ("Prefeitura de Alagoa Grande", "Alagoa Grande", "https://www.alagoagrande.pb.gov.br/portal-da-transparencia/"),
    ("Prefeitura de Caaporã", "Caaporã", "https://www.caapora.pb.gov.br/transparencia"),
    ("Prefeitura de Mari", "Mari", "https://mari.pb.gov.br/transparencia/"),
    ("Prefeitura de Pitimbu", "Pitimbu", "https://www.pitimbu.pb.gov.br/transparencia-fiscal"),
    ("Prefeitura de Aroeiras", "Aroeiras", "http://www.aroeiras.pb.gov.br/transparencia"),
    ("Prefeitura de Pocinhos", "Pocinhos", "https://pocinhos.pb.gov.br/transparencia/"),
    ("Prefeitura de Picui", "Picui", "https://www.picui.pb.gov.br/portal/transparencia-fiscal"),
    ("Prefeitura de Taperoá", "Taperoá", "https://taperoa.pb.gov.br/assuntos/portal-da-transparencia"),
    ("Prefeitura de Gurinhém", "Gurinhém", "https://www.gurinhem.pb.gov.br/portal-da-transparencia/"),
    ("Prefeitura de Massaranduba", "Massaranduba", "https://www.massaranduba.pb.gov.br/Site/Transparencia"),
    ("Prefeitura de São Sebastião de Lagoa de Roça", "São Sebastião de Lagoa de Roça ", "https://www.transparenciaativa.com.br/Principal.aspx?Entidade=99&Ano=2023"),
    ("Prefeitura de Tacima", "Tacima", "https://pmtacima.pb.gov.br/portal-da-transparencia/"),
    ("Prefeitura de Umbuzeiro", "Umbuzeiro", "https://transparenciaativa.com.br/Principal.aspx?Entidade=189"),
    ("Prefeitura de Gado Bravo", "Gado Bravo", "https://www.gadobravo.pb.gov.br/transparencia"),
    ("Prefeitura de Guarabira", "Guarabira", "https://guarabira.pb.gov.br/pagina/portal-da-transparencia"),
    ("Prefeitura de São Bento", "São Bento", "https://transparencia.saobento.pb.gov.br/"),
    ("Prefeitura de Conde", "Conde", "https://www.conde.pb.gov.br/portal-da-transparencia/"),
    ("Prefeitura de Itabaiana", "Itabaiana", "https://transparencia.itabaiana.pb.gov.br/"),
    ("Prefeitura de Princesa Isabel", "Princesa Isabel", "https://www.princesa.pb.gov.br/portal/transparencia-fiscal"),
    ("Prefeitura de São José de Piranhas", "São José de Piranhas", "https://www.saojosedepiranhas.pb.gov.br/transparencia.html"),
    ("Prefeitura de Cuité", "Cuité", "https://cuite.pb.gov.br/portal-da-transparencia/"),
    ("Prefeitura de Ingá", "Ingá", "https://www.inga.pb.gov.br/transparencia-fiscal"),
    ("Prefeitura de São João do Rio do Peixe", "São João do Rio do Peixe", "https://www.sjrp.pb.gov.br/transparenciafiscal.php"),
    ("Prefeitura de Belém", "Belém", "https://belem.pb.gov.br/portal-da-transparencia/"),
    ("Prefeitura de Sumé", "Sumé", "https://www.sume.pb.gov.br/transparencia/"),
    ("Prefeitura de Barra de Santa Rosa", "Barra de Santa Rosa", "https://www.barradesantarosa.pb.gov.br/portal/transparencia-fiscal"),
    ("Prefeitura de Jacaraú", "Jacaraú", "https://jacarau.pb.gov.br/portal-da-transparencia/"),
    ("Prefeitura de Arara", "Arara", "https://transparencia.elmartecnologia.com.br/?e=201012"),
    ("Prefeitura de Salgado de São Félix", "Salgado de São Félix", "https://salgadosaofelix.pb.gov.br/portal-da-transparencia/"),
    ("Prefeitura de Fagundes", "Fagundes", "https://fagundes.pb.gov.br/transparencia-fiscal"),
    ("Prefeitura de Itatuba", "Itatuba", "https://itatuba.pb.gov.br/transparencia-fiscal"),
    ("Prefeitura de Jericó", "Jericó", "https://jerico.pb.gov.br/transparenciafiscal.php"),
    ("Prefeitura de Brejo dos Santos", "Brejo dos Santos", "https://transparencia.brejodossantos.pb.gov.br/"),
    ("Prefeitura de Natuba", "Natuba", "https://www.natuba.pb.gov.br/transparencia/"),
    ("Prefeitura de Juripiranga", "Juripiranga", "https://www.juripiranga.pb.gov.br/portal/transparencia-fiscal"),
]

print('Creating tables...', end=' ')
db.create_tables([ManagementUnit, Evaluation])
print('ok')

print('Adding data from managing units...')
for name, public_entity, start_urls in DATA:
    print(name, end=': ')

    mu = ManagementUnit.get_or_none(ManagementUnit.name == name)

    if mu:
        if mu.start_urls != start_urls:
            mu.start_urls = start_urls
            mu.save()
            print('updated.')
        else:
            print('already exists.')
    else:
        try:
            mu = ManagementUnit(name=name, public_entity=public_entity, start_urls=start_urls)
            mu.save()
        except peewee.IntegrityError:
            db.rollback()
            print('already exists.')
        else:
            print('added.')
